service: looker-embed-purge

# app and org for use with dashboard.serverless.com
app: looker-embed-purge
org: mtwomey

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

  stage: prod
  region: us-east-1

functions:
  lookerEmbedPurge:
    handler: handler.lookerEmbedPurge
    name: looker-embed-purge
    events:
      - schedule: cron(17 0 * * ? *)
